//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace UnitTestProject1.EF4Behaviour
{
    public partial class Model1Container : ObjectContext
    {
        public const string ConnectionString = "name=Model1Container";
        public const string ContainerName = "Model1Container";
    
        #region Constructors
    
        public Model1Container()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public Model1Container(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public Model1Container(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<EFMaster> EFMasterSet
        {
            get { return _eFMasterSet  ?? (_eFMasterSet = CreateObjectSet<EFMaster>("EFMasterSet")); }
        }
        private ObjectSet<EFMaster> _eFMasterSet;
    
        public ObjectSet<EF4Detail> EF4DetailSet
        {
            get { return _eF4DetailSet  ?? (_eF4DetailSet = CreateObjectSet<EF4Detail>("EF4DetailSet")); }
        }
        private ObjectSet<EF4Detail> _eF4DetailSet;
    
        public ObjectSet<EF4SurrogateDetail> EF4SurrogateDetail
        {
            get { return _eF4SurrogateDetail  ?? (_eF4SurrogateDetail = CreateObjectSet<EF4SurrogateDetail>("EF4SurrogateDetail")); }
        }
        private ObjectSet<EF4SurrogateDetail> _eF4SurrogateDetail;
    
        public ObjectSet<EFMasterSurrogate> EFMasterSurrogate
        {
            get { return _eFMasterSurrogate  ?? (_eFMasterSurrogate = CreateObjectSet<EFMasterSurrogate>("EFMasterSurrogate")); }
        }
        private ObjectSet<EFMasterSurrogate> _eFMasterSurrogate;

        #endregion

    }
}
