//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace UnitTestProject1.EF4Behaviour
{
    public partial class EFMaster
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual string MyProperty
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual ICollection<EF4Detail> EF4Detail
        {
            get
            {
                if (_eF4Detail == null)
                {
                    var newCollection = new FixupCollection<EF4Detail>();
                    newCollection.CollectionChanged += FixupEF4Detail;
                    _eF4Detail = newCollection;
                }
                return _eF4Detail;
            }
            set
            {
                if (!ReferenceEquals(_eF4Detail, value))
                {
                    var previousValue = _eF4Detail as FixupCollection<EF4Detail>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupEF4Detail;
                    }
                    _eF4Detail = value;
                    var newValue = value as FixupCollection<EF4Detail>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupEF4Detail;
                    }
                }
            }
        }
        private ICollection<EF4Detail> _eF4Detail;

        #endregion

        #region Association Fixup
    
        private void FixupEF4Detail(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (EF4Detail item in e.NewItems)
                {
                    item.EFMaster = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (EF4Detail item in e.OldItems)
                {
                    if (ReferenceEquals(item.EFMaster, this))
                    {
                        item.EFMaster = null;
                    }
                }
            }
        }

        #endregion

    }
}
